name: deb packaging

on:
  push:
    tags:
      - 'debian/*.*.*-*'
      - 'test/*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  DEBFULLNAME: dionysius (github actions)
  DEBEMAIL: "dragon.dionysius+gha@gmail.com"

jobs:

  build-native:
    uses: dionysius/gbp-gha/gbp-native.yml@main
  build-qemu:
    uses: dionysius/gbp-gha/gbp-qemu.yml@main
  release:
    uses: dionysius/gbp-gha/release.yml@main
