name: deb packaging

on:
  push:
    tags:
      - 'debian/*.*.*-*'
      - 'test/*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-native:
    uses: dionysius/gbp-gha/.github/workflows/gbp-native.yml@main
  # build-qemu:
  #   uses: dionysius/gbp-gha/.github/workflows/gbp-qemu.yml@main
  release:
    if: startsWith(github.event.ref, 'refs/tags/debian') || startsWith(github.event.ref, 'refs/tags/test')
    needs: [build-native]
    uses: dionysius/gbp-gha/.github/workflows/release.yml@main
